name: Update README

on:
  schedule:
    - cron: '0 * * * *'  # This runs every hour
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Update README with latest blog posts
        uses: gautamkrishnar/blog-post-workflow@v1.0.0
        with:
          feed_list: "https://medium.com/feed/@manojtharindu11"
