name: Update README with Latest Medium Article

on:
  schedule:
    - cron: '0 * * * *'  # Runs every hour, adjust as needed
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Fetch Latest Medium Article
        id: fetch-article
        run: |
          article=$(curl -s https://medium.com/@manojtharindu11/latest?format=json | grep -o '"title":[^,]*' | head -n 1 | cut -d '"' -f 4)
          echo "Latest Medium Article: $article"
          sed -i 's/BLOG-POST-LIST:START.*BLOG-POST-LIST:END/BLOG-POST-LIST:START\n- [Update README]($article)\nBLOG-POST-LIST:END/' README.md

      - name: Commit and Push Changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add README.md
          git commit -m "Update README with latest Medium article"
          git push https://github.com/${{ github.repository }} HEAD:main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
