name: Update README with Latest Medium Article

on:
  schedule:
    - cron: '0 * * * *'  # Runs every hour, adjust as needed
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Fetch Latest Medium Article
        id: fetch-article
        run: |
          # Fetch the latest Medium article title
          article=$(curl -s https://medium.com/@manojtharindu11/latest?format=json | grep -o '"title":[^,]*' | head -n 1 | cut -d '"' -f 4)
          echo "Latest Medium Article: $article"
          echo "<h3 align='left'>Latest Medium Article:</h3>" > README.md
          echo "<p align='left'>$article</p>" >> README.md

      - name: Commit and Push Changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add README.md
          git commit -m "Update README with latest Medium article"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
